# Generated by Django 4.1.6 on 2023-03-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGenerica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='nacimiento',
            field=models.IntegerField(),
        ),
    ]
